# Site settings
title: Deft Blog
SEOTitle: Deft的博客 | Deft Blog
header-img: img/post-bg-universe.jpg
email: deftmail@163.com
description: "To be both a speaker of words and a doer of deeds."
keyword: "Deft Blog, Deft的博客, Deft, web, JavaScript, TS, 个人网站, 互联网, Web, 前端"
url: "http://louliang11.gitee.io"              # your host, for absolute URL
baseurl: "/blog"                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     deftliang
# zhihu_username:     deftliang
github_username:    deftliang
twitter_username:   louliang
#facebook_username:  deftliang
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: lou-leung

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: deftliang.github.io    #仓库名称
  owner: deftliang   #github用户名
  admin: deftliang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: ''            # Format: UA-xxxxxx-xx
# ga_domain: #



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: /img/avatar_df.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    # {
    #     title: "乱序（Midare）",
    #     href: "http://mida.re/"
    # },{
    #     title: "Sherry Woo",
    #     href: "https://sherrywoo.me/"
    # },{
    #     title: "Kun Qian",
    #     href: "http://kunq.me"
    # },{
    #     title: "Ebn Zhang",
    #     href: "http://ebnbin.com/"
    # },{
    #     title: "SmdCn",
    #     href: "http://blog.smdcn.net"
    # },{
    #     title: "JiyinYiyong",
    #     href: "http://tiye.me/"
    # },{
    #     title: "DHong Say",
    #     href: "http://dhong.co"
    # },{
    #     title: "尹峰以为",
    #     href: "http://ingf.github.io/"
    # }
    {
        title: "FreeCodeCamp",
        href: "https://learn.freecodecamp.one/"
    },{
        title: "Bootstrap",
        href: "https://www.bootcss.com/"
    },{
        title: "掘金",
        href: "https://juejin.im/"
    },{
        title: "开发者头条",
        href: "https://toutiao.io/posts/hot/7"
    },{
        title: "Readhub",
        href: "https://readhub.cn/topics"
    },{
        title: "OSCHINA",
        href: "https://www.oschina.net/"
    }
]
